# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo running terraform
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure resource manager connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tfstate'
    backendAzureRmResourceGroupLocation: 'East US'
    backendAzureRmStorageAccountName: 'tfstatefs18m'
    backendAzureRmContainerName: 'azvmresource'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure resource manager connection'
    allowTelemetryCollection: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      terraform output -raw tls_private_key > id_rsa
      terraform output public_ip_address